graph TD
    classDef module fill:#f9f,stroke:#333,stroke-width:2px;
    settings_model
    class settings_model module;
    config
    class config module;
    data_cache
    class data_cache module;
    geology_interface
    class geology_interface module;
    exceptions
    class exceptions module;
    reproduce_proxy
    class reproduce_proxy module;
    dtos
    class dtos module;
    task_inputs
    class task_inputs module;
    structure_interface
    class structure_interface module;
    performance_metrics
    class performance_metrics module;
    spatial_meta
    class spatial_meta module;
    cache_interface
    class cache_interface module;
    drillhole_interface
    class drillhole_interface module;
    algorithms
    class algorithms module;
    enums
    class enums module;
    entities
    class entities module;
    controller
    class controller module;
    profile_interface
    class profile_interface module;
    i_renderer_3d
    class i_renderer_3d module;
    preview_interface
    class preview_interface module;
