import xml.etree.ElementTree as ET
from pathlib import Path

langs = {
    "es": {
        "Adaptive": "Adaptativo",
        "Add Field": "Añadir Campo",
        "Advanced": "Avanzado",
        "An unexpected error occurred: {}": "Ocurrió un error inesperado: {}",
        "Attribute Inheritance": "Herencia de Atributos",
        "Auto": "Auto",
        "Auto-inherit from Drillhole intervals": "Auto-heredar de intervalos de sondaje",
        "Auto-inherit from Geology layers": "Auto-heredar de capas de geología",
        "Automatically adjust details based on preview size": "Ajustar detalles automáticamente según tamaño",
        "Automatically copy rock code and attributes from the nearest drillhole interval.": "Copiar código roca y atributos del intervalo más cercano.",
        "Automatically copy unit name and attributes from the nearest geology segment.": "Copiar nombre unidad y atributos del segmento más cercano.",
        "✓ Cache cleared - next preview will re-process data": "✓aché limpio. La próxima vista reprocesará datos",
        "⚠ Cache not available": "⚠ Caché no disponible",
        "Change...": "Cambiar...",
        "Clear cached data to force re-processing.": "Limpiar caché para forzar reprocesamiento.",
        "Color:": "Color:",
        "Configuration Error": "Error de Configuración",
        "Contact: {metadata['email']}": "Contacto: {metadata['email']}",
        "Coords: - , -": "Coords: - , -",
        "Cross-section line layer is required": "Se requiere capa de línea de sección",
        "CRS: -": "CRS: -",
        "CRS: {}": "CRS: {}",
        "CRS: None": "CRS: Ninguno",
        "CRS: Unknown": "CRS: Desconocido",
        "Custom Attributes": "Atributos Personalizados",
        "Default": "Por Defecto",
        "Default Value": "Valor por Defecto",
        "DEM / Raster": "DEM / Ráster",
        "Developed by {metadata['author']}": "Desarrollado por {metadata['author']}",
        "  Distance: {} to {} m": "  Distancia: {} a {} m",
        "Draw interpretation polygons": "Dibujar polígonos de interpretación",
        "Drillhole configuration is incomplete": "Configuración de sondajes incompleta",
        "Drillhole Data": "Datos de Sondaje",
        "Drillholes": "Sondajes",
        "Drillholes: {} holes found": "Sondajes: {} encontrados",
        "Drillholes: No data": "Sondajes: Sin datos",
        "Duplicate field name: {}": "Nombre de campo duplicado: {}",
        "  Elevation: {} to {} m": "  Elevación: {} a {} m",
        "Enable 3D Interpretation Export": "Habilitar Exportación 3D",
        "Enables the generation of 3D Shapefiles (.shp) during export.": "Habilita generación de Shapefiles 3D (.shp) al exportar.",
        "Error": "Error",
        "Export 3D Intervals": "Exportar Intervalos 3D",
        "Export 3D Traces": "Exportar Trazas 3D",
        "Export Error": "Error de Exportación",
        "Export preview to file": "Exportar vista previa a archivo",
        "Field Name": "Nombre del Campo",
        "Field name cannot be empty": "El nombre del campo no puede estar vacío",
        "Finalize": "Finalizar",
        "Finalize multi-point measurement": "Finalizar medición multipunto",
        "✓ Form reset to default values": "✓ Formulario reiniciado a valores por defecto",
        "Generating Drillholes in background...": "Generando Sondajes en segundo plano...",
        "Generating Geology: {}%...": "Generando Geología: {}%...",
        "Generating Geology in background...": "Generando Geología en segundo plano...",
        "Geological Profile": "Perfil Geológico",
        "Geology": "Geología",
        "Geology configuration is incomplete": "Configuración geológica incompleta",
        "Geology: No data": "Geología: Sin datos",
        "Geology processing failed: {}": "Fallo en procesamiento geológico: {}",
        "Geology: {} segments": "Geología: {} segmentos",
        "Geometry Range:": "Rango Geometría:",
        "Help file not found. Please run 'make doc' to generate it.": "Archivo de ayuda no encontrado. Ejecute 'make doc'.",
        "Input Processing Error": "Error de Procesamiento de Entrada",
        "Interpret": "Interpretar",
        "Interpretation": "Interpretación",
        "Interpretation Properties": "Propiedades de Interpretación",
        "Interpretations (2D)": "Interpretaciones (2D)",
        "Interpretation Settings": "Configuración de Interpretación",
        "Invalid configuration": "Configuración inválida",
        "<i>Select which data to generate when clicking Save.</i>": "<i>Seleccione qué datos generar al Guardar.</i>",
        " m": " m",
        "Maximum points to render in preview (LOD Optimization)": "Puntos máximos en vista previa (LOD)",
        "Max Points:": "Puntos Max:",
        "Measure": "Medir",
        "Measure distance and slope": "Medir distancia y pendiente",
        "{metadata['name']} v{metadata['version']}": "{metadata['name']} v{metadata['version']}",
        "Metadata missing": "Metadatos faltantes",
        "Name:": "Nombre:",
        "New Interpretation": "Nueva Interpretación",
        "No layers to export.": "Sin capas para exportar.",
        "No preview available to export. Generate a preview first.": "Sin vista previa para exportar. Genere una primero.",
        "No profile data generated.": "Sin datos de perfil generados.",
        "Output directory path is required": "Ruta de directorio de salida requerida",
        "Output Folder": "Carpeta de Salida",
        "Performance:": "Rendimiento:",
        "Plugin Information": "Información del Plugin",
        "Plugin Settings": "Ajustes del Plugin",
        "Preview Error": "Error de Vista Previa",
        "Preview exported to {}": "Vista previa exportada a {}",
        "✓ Preview generated!": "✓ Vista previa generada!",
        "Preview generated successfully": "Vista previa generada con éxito",
        "Raster DEM layer is required": "Capa raster DEM requerida",
        "Raster layer selected": "Capa ráster seleccionada",
        "Remove Field": "Eliminar Campo",
        "Reset all inputs to their default values.": "Reiniciar todo a valores por defecto.",
        "Reset Defaults": "Restaurar Defaults",
        "Scale 1: -": "Escala 1: -",
        "Scale 1:{}": "Escala 1:{}",
        "Sec Interp": "Sec Interp",
        "Sec Interp (version unavailable)": "Sec Interp (versión no disponible)",
        "Section Line": "Línea de Sección",
        "Section line selected": "Línea de sección seleccionada",
        "Select Color": "Seleccionar Color",
        "Settings": "Ajustes",
        "Show Interpretations": "Mostrar Interpretaciones",
        "Show Legend": "Mostrar Leyenda",
        "Structural": "Estructural",
        "Structural Data": "Datos Estructurales",
        "Structure configuration is incomplete": "Configuración estructural incompleta",
        "Structures: {} measurements (buffer: {}m)": "Estructuras: {} medidas (buffer: {}m)",
        "Structures: No data": "Estructuras: Sin datos",
        "Success": "Éxito",
        "Topographic Profile": "Perfil Topográfico",
        "Topography: {} points": "Topografía: {} puntos",
        "Type": "Tipo",
        "Type:": "Tipo:",
        "Use adaptive sampling based on curvature (Phase 2)": "Muestreo adaptativo por curvatura (Fase 2)",
        "Use Original Coordinates (Real 3D)": "Usar Coordenadas Originales (3D Real)",
        "Use Projected Coordinates (Section Plane)": "Usar Coordenadas Proyectadas (Plano Sección)",
        "Validation Error": "Error de Validación",
        "{}\n\nPlease check the logs for details.": "{}\n\nPor favor, revise los logs para más detalles.",
    },
    "fr": {
        "Adaptive": "Adaptatif",
        "Add Field": "Ajouter Champ",
        "Advanced": "Avancé",
        "An unexpected error occurred: {}": "Une erreur inattendue est survenue: {}",
        "Attribute Inheritance": "Héritage d'attributs",
        "Auto": "Auto",
        "Auto-inherit from Drillhole intervals": "Hériter des intervalles de forage",
        "Auto-inherit from Geology layers": "Hériter des couches géologiques",
        "Automatically adjust details based on preview size": "Ajuster détails selon taille aperçu",
        "Automatically copy rock code and attributes from the nearest drillhole interval.": "Copier auto code roche/attributs intervalle proche.",
        "Automatically copy unit name and attributes from the nearest geology segment.": "Copier auto nom unité/attributs segment proche.",
        "✓ Cache cleared - next preview will re-process data": "✓ Cache vidé - prochain aperçu re-traitera données",
        "⚠ Cache not available": "⚠ Cache non disponible",
        "Change...": "Changer...",
        "Clear cached data to force re-processing.": "Vider cache pour forcer re-traitement.",
        "Color:": "Couleur:",
        "Configuration Error": "Erreur Configuration",
        "Contact: {metadata['email']}": "Contact: {metadata['email']}",
        "Coords: - , -": "Coords: - , -",
        "Cross-section line layer is required": "Couche ligne de coupe requise",
        "CRS: -": "CRS: -",
        "CRS: {}": "CRS: {}",
        "CRS: None": "CRS: Aucun",
        "CRS: Unknown": "CRS: Inconnu",
        "Custom Attributes": "Attributs Personnalisés",
        "Default": "Défaut",
        "Default Value": "Valeur par Défaut",
        "DEM / Raster": "MNT / Raster",
        "Developed by {metadata['author']}": "Développé par {metadata['author']}",
        "  Distance: {} to {} m": "  Distance: {} à {} m",
        "Draw interpretation polygons": "Dessiner polygones interprétation",
        "Drillhole configuration is incomplete": "Config forage incomplète",
        "Drillhole Data": "Données Forage",
        "Drillholes": "Forages",
        "Drillholes: {} holes found": "Forages: {} trouvés",
        "Drillholes: No data": "Forages: Pas de données",
        "Duplicate field name: {}": "Nom champ dupliqué: {}",
        "  Elevation: {} to {} m": "  Élévation: {} à {} m",
        "Enable 3D Interpretation Export": "Activer Export 3D",
        "Enables the generation of 3D Shapefiles (.shp) during export.": "Active génération Shapefiles 3D (.shp) lors export.",
        "Error": "Erreur",
        "Export 3D Intervals": "Exporter Intervalles 3D",
        "Export 3D Traces": "Exporter Traces 3D",
        "Export Error": "Erreur Export",
        "Export preview to file": "Exporter aperçu vers fichier",
        "Field Name": "Nom du Champ",
        "Field name cannot be empty": "Nom du champ ne peut être vide",
        "Finalize": "Finaliser",
        "Finalize multi-point measurement": "Finaliser mesure multi-points",
        "✓ Form reset to default values": "✓ Formulaire réinitialisé",
        "Generating Drillholes in background...": "Génération Forages en arrière-plan...",
        "Generating Geology: {}%...": "Génération Géologie: {}%...",
        "Generating Geology in background...": "Génération Géologie en arrière-plan...",
        "Geological Profile": "Profil Géologique",
        "Geology": "Géologie",
        "Geology configuration is incomplete": "Config géologie incomplète",
        "Geology: No data": "Géologie: Pas de données",
        "Geology processing failed: {}": "Échec traitement géologie: {}",
        "Geology: {} segments": "Géologie: {} segments",
        "Geometry Range:": "Plage Géométrie:",
        "Help file not found. Please run 'make doc' to generate it.": "Fichier aide introuvable. Exécuter 'make doc'.",
        "Input Processing Error": "Erreur Traitement Entrée",
        "Interpret": "Interpréter",
        "Interpretation": "Interprétation",
        "Interpretation Properties": "Propriétés Interprétation",
        "Interpretations (2D)": "Interprétations (2D)",
        "Interpretation Settings": "Paramètres Interprétation",
        "Invalid configuration": "Configuration invalide",
        "<i>Select which data to generate when clicking Save.</i>": "<i>Sélectionner données à générer au Sauvegarder.</i>",
        " m": " m",
        "Maximum points to render in preview (LOD Optimization)": "Points max aperçu (LOD)",
        "Max Points:": "Points Max:",
        "Measure": "Mesurer",
        "Measure distance and slope": "Mesurer distance et pente",
        "{metadata['name']} v{metadata['version']}": "{metadata['name']} v{metadata['version']}",
        "Metadata missing": "Métadonnées manquantes",
        "Name:": "Nom:",
        "New Interpretation": "Nouvelle Interprétation",
        "No layers to export.": "Aucune couche à exporter.",
        "No preview available to export. Generate a preview first.": "Pas d'aperçu à exporter. Générer d'abord.",
        "No profile data generated.": "Aucune donnée profil générée.",
        "Output directory path is required": "Chemin dossier sortie requis",
        "Output Folder": "Dossier Sortie",
        "Performance:": "Performance:",
        "Plugin Information": "Informations Plugin",
        "Plugin Settings": "Paramètres Plugin",
        "Preview Error": "Erreur Aperçu",
        "Preview exported to {}": "Aperçu exporté vers {}",
        "✓ Preview generated!": "✓ Aperçu généré!",
        "Preview generated successfully": "Aperçu généré avec succès",
        "Raster DEM layer is required": "Couche MNT requise",
        "Raster layer selected": "Couche raster sélectionnée",
        "Remove Field": "Supprimer Champ",
        "Reset all inputs to their default values.": "Réinitialiser valeurs par défaut.",
        "Reset Defaults": "Réinit. Défaut",
        "Scale 1: -": "Échelle 1: -",
        "Scale 1:{}": "Échelle 1:{}",
        "Sec Interp": "Sec Interp",
        "Sec Interp (version unavailable)": "Sec Interp (version indisponible)",
        "Section Line": "Ligne de Coupe",
        "Section line selected": "Ligne de coupe sélectionnée",
        "Select Color": "Choisir Couleur",
        "Settings": "Paramètres",
        "Show Interpretations": "Montrer Interprétations",
        "Show Legend": "Montrer Légende",
        "Structural": "Structurel",
        "Structural Data": "Données Structurelles",
        "Structure configuration is incomplete": "Config structure incomplète",
        "Structures: {} measurements (buffer: {}m)": "Structures: {} mesures (tampon: {}m)",
        "Structures: No data": "Structures: Pas de données",
        "Success": "Succès",
        "Topographic Profile": "Profil Topographique",
        "Topography: {} points": "Topographie: {} points",
        "Type": "Type",
        "Type:": "Type:",
        "Use adaptive sampling based on curvature (Phase 2)": "Échantillonnage adaptatif (Phase 2)",
        "Use Original Coordinates (Real 3D)": "Unit. Coordonnées Originales (Vrai 3D)",
        "Use Projected Coordinates (Section Plane)": "Util. Coordonnées Projetées (Plan Coupe)",
        "Validation Error": "Erreur Validation",
        "{}\n\nPlease check the logs for details.": "{}\n\nVeuillez vérifier les logs pour plus de détails.",
    },
    "pt_BR": {
        "Adaptive": "Adaptativo",
        "Add Field": "Adicionar Campo",
        "Advanced": "Avançado",
        "An unexpected error occurred: {}": "Erro inesperado ocorreu: {}",
        "Attribute Inheritance": "Herança de Atributos",
        "Auto": "Auto",
        "Auto-inherit from Drillhole intervals": "Auto-herdar invervalos sondagem",
        "Auto-inherit from Geology layers": "Auto-herdar camadas geologia",
        "Automatically adjust details based on preview size": "Ajuste automático detalhes por tamanho",
        "Automatically copy rock code and attributes from the nearest drillhole interval.": "Copiar auto cód. rocha/atributos intervalo próx.",
        "Automatically copy unit name and attributes from the nearest geology segment.": "Copiar auto nome unidade/atributos segmento próx.",
        "✓ Cache cleared - next preview will re-process data": "✓ Cache limpo - próx prévia reprocessará dados",
        "⚠ Cache not available": "⚠ Cache não disponível",
        "Change...": "Alterar...",
        "Clear cached data to force re-processing.": "Limpar cache para forçar reprocessamento.",
        "Color:": "Cor:",
        "Configuration Error": "Erro Configuração",
        "Contact: {metadata['email']}": "Contato: {metadata['email']}",
        "Coords: - , -": "Coords: - , -",
        "Cross-section line layer is required": "Camada linha seção necessária",
        "CRS: -": "CRS: -",
        "CRS: {}": "CRS: {}",
        "CRS: None": "CRS: Nenhum",
        "CRS: Unknown": "CRS: Desconhecido",
        "Custom Attributes": "Atributos Personalizados",
        "Default": "Padrão",
        "Default Value": "Valor Padrão",
        "DEM / Raster": "MDE / Raster",
        "Developed by {metadata['author']}": "Desenvolvido por {metadata['author']}",
        "  Distance: {} to {} m": "  Distância: {} a {} m",
        "Draw interpretation polygons": "Desenhar polígonos interpretação",
        "Drillhole configuration is incomplete": "Config sondagem incompleta",
        "Drillhole Data": "Dados Sondagem",
        "Drillholes": "Sondagens",
        "Drillholes: {} holes found": "Sondagens: {} encontrados",
        "Drillholes: No data": "Sondagens: Sem dados",
        "Duplicate field name: {}": "Nome campo duplicado: {}",
        "  Elevation: {} to {} m": "  Elevação: {} a {} m",
        "Enable 3D Interpretation Export": "Habilitar Exportação 3D",
        "Enables the generation of 3D Shapefiles (.shp) during export.": "Habilita geração Shapefiles 3D (.shp) na exportação.",
        "Error": "Erro",
        "Export 3D Intervals": "Exportar Intervalos 3D",
        "Export 3D Traces": "Exportar Traços 3D",
        "Export Error": "Erro Exportação",
        "Export preview to file": "Exportar prévia para arquivo",
        "Field Name": "Nome do Campo",
        "Field name cannot be empty": "Nome do campo não pode ser vazio",
        "Finalize": "Finalizar",
        "Finalize multi-point measurement": "Finalizar medição multiponto",
        "✓ Form reset to default values": "✓ Formulário reiniciado",
        "Generating Drillholes in background...": "Gerando Sondagens em segundo plano...",
        "Generating Geology: {}%...": "Gerando Geologia: {}%...",
        "Generating Geology in background...": "Gerando Geologia em segundo plano...",
        "Geological Profile": "Perfil Geológico",
        "Geology": "Geologia",
        "Geology configuration is incomplete": "Config geologia incompleta",
        "Geology: No data": "Geologia: Sem dados",
        "Geology processing failed: {}": "Falha proc. geologia: {}",
        "Geology: {} segments": "Geologia: {} segmentos",
        "Geometry Range:": "Faixa Geometria:",
        "Help file not found. Please run 'make doc' to generate it.": "Arquivo ajuda não encontrado. Execute 'make doc'.",
        "Input Processing Error": "Erro Proc. Entrada",
        "Interpret": "Interpretar",
        "Interpretation": "Interpretação",
        "Interpretation Properties": "Propriedades Interpretação",
        "Interpretations (2D)": "Interpretações (2D)",
        "Interpretation Settings": "Config Interpretação",
        "Invalid configuration": "Configuração inválida",
        "<i>Select which data to generate when clicking Save.</i>": "<i>Selecione dados a gerar ao Salvar.</i>",
        " m": " m",
        "Maximum points to render in preview (LOD Optimization)": "Max pontos prévia (LOD)",
        "Max Points:": "Max Pontos:",
        "Measure": "Medir",
        "Measure distance and slope": "Medir distância e inclinação",
        "{metadata['name']} v{metadata['version']}": "{metadata['name']} v{metadata['version']}",
        "Metadata missing": "Metadados ausentes",
        "Name:": "Nome:",
        "New Interpretation": "Nova Interpretação",
        "No layers to export.": "Sem camadas para exportar.",
        "No preview available to export. Generate a preview first.": "Sem prévia para exportar. Gere primeiro.",
        "No profile data generated.": "Nenhum dado de perfil gerado.",
        "Output directory path is required": "Caminho diretório saída obrigatório",
        "Output Folder": "Pasta Saída",
        "Performance:": "Desempenho:",
        "Plugin Information": "Informações Plugin",
        "Plugin Settings": "Configurações Plugin",
        "Preview Error": "Erro Prévia",
        "Preview exported to {}": "Prévia exportada para {}",
        "✓ Preview generated!": "✓ Prévia gerada!",
        "Preview generated successfully": "Prévia gerada com sucesso",
        "Raster DEM layer is required": "Camada raster MDE necessária",
        "Raster layer selected": "Camada raster selecionada",
        "Remove Field": "Remover Campo",
        "Reset all inputs to their default values.": "Reiniciar tudo para padrão.",
        "Reset Defaults": "Restaurar Padrão",
        "Scale 1: -": "Escala 1: -",
        "Scale 1:{}": "Escala 1:{}",
        "Sec Interp": "Sec Interp",
        "Sec Interp (version unavailable)": "Sec Interp (versão indisponível)",
        "Section Line": "Linha Seção",
        "Section line selected": "Linha seção selecionada",
        "Select Color": "Selecionar Cor",
        "Settings": "Configurações",
        "Show Interpretations": "Mostrar Interpretações",
        "Show Legend": "Mostrar Legenda",
        "Structural": "Estrutural",
        "Structural Data": "Dados Estruturais",
        "Structure configuration is incomplete": "Config estrutura incompleta",
        "Structures: {} measurements (buffer: {}m)": "Estruturas: {} medidas (buffer: {}m)",
        "Structures: No data": "Estruturas: Sem dados",
        "Success": "Sucesso",
        "Topographic Profile": "Perfil Topográfico",
        "Topography: {} points": "Topografia: {} pontos",
        "Type": "Tipo",
        "Type:": "Tipo:",
        "Use adaptive sampling based on curvature (Phase 2)": "Amostragem adaptativa curvatura (Fase 2)",
        "Use Original Coordinates (Real 3D)": "Usar Coordenadas Originais (3D Real)",
        "Use Projected Coordinates (Section Plane)": "Usar Coordenadas Projetadas (Plano Seção)",
        "Validation Error": "Erro Validação",
        "{}\n\nPlease check the logs for details.": "{}\n\nPor favor, verifique os logs para detalhes.",
    },
    "de": {
        "Adaptive": "Adaptiv",
        "Add Field": "Feld Hinzufügen",
        "Advanced": "Erweitert",
        "An unexpected error occurred: {}": "Unerwarteter Fehler aufgetreten: {}",
        "Attribute Inheritance": "Attributvererbung",
        "Auto": "Auto",
        "Auto-inherit from Drillhole intervals": "Auto-Vererbung von Bohrlochintervallen",
        "Auto-inherit from Geology layers": "Auto-Vererbung von Geologicschichten",
        "Automatically adjust details based on preview size": "Automatische Detailanpassung nach Größe",
        "Automatically copy rock code and attributes from the nearest drillhole interval.": "Kopiere Gesteinscode/Attribute vom nächsten Bohrloch.",
        "Automatically copy unit name and attributes from the nearest geology segment.": "Kopiere Einheitsname/Attribute vom nächsten Segment.",
        "✓ Cache cleared - next preview will re-process data": "✓ Cache geleert - nächste Vorschau verarbeitet neu",
        "⚠ Cache not available": "⚠ Cache nicht verfügbar",
        "Change...": "Ändern...",
        "Clear cached data to force re-processing.": "Cache leeren um Neuverarbeitung zu erzwingen.",
        "Color:": "Farbe:",
        "Configuration Error": "Konfigurationsfehler",
        "Contact: {metadata['email']}": "Kontakt: {metadata['email']}",
        "Coords: - , -": "Koords: - , -",
        "Cross-section line layer is required": "Profillinien-Layer erforderlich",
        "CRS: -": "KBS: -",
        "CRS: {}": "KBS: {}",
        "CRS: None": "KBS: Keines",
        "CRS: Unknown": "KBS: Unbekannt",
        "Custom Attributes": "Benutzerdef. Attribute",
        "Default": "Standard",
        "Default Value": "Standardwert",
        "DEM / Raster": "DGM / Raster",
        "Developed by {metadata['author']}": "Entwickelt von {metadata['author']}",
        "  Distance: {} to {} m": "  Entfernung: {} bis {} m",
        "Draw interpretation polygons": "Interpretationspolygone zeichnen",
        "Drillhole configuration is incomplete": "Bohrlochkonfiguration unvollständig",
        "Drillhole Data": "Bohrlochdaten",
        "Drillholes": "Bohrlöcher",
        "Drillholes: {} holes found": "Bohrlöcher: {} gefunden",
        "Drillholes: No data": "Bohrlöcher: Keine Daten",
        "Duplicate field name: {}": "Doppelter Feldname: {}",
        "  Elevation: {} to {} m": "  Höhe: {} bis {} m",
        "Enable 3D Interpretation Export": "3D-Export aktivieren",
        "Enables the generation of 3D Shapefiles (.shp) during export.": "Aktiviert Erstellung von 3D-Shapefiles beim Export.",
        "Error": "Fehler",
        "Export 3D Intervals": "3D-Intervalle exportieren",
        "Export 3D Traces": "3D-Spuren exportieren",
        "Export Error": "Exportfehler",
        "Export preview to file": "Vorschau in Datei exportieren",
        "Field Name": "Feldname",
        "Field name cannot be empty": "Feldname darf nicht leer sein",
        "Finalize": "Abschließen",
        "Finalize multi-point measurement": "Mehrpunktmessung abschließen",
        "✓ Form reset to default values": "✓ Formular zurückgesetzt",
        "Generating Drillholes in background...": "Generiere Bohrlöcher im Hintergrund...",
        "Generating Geology: {}%...": "Generiere Geologie: {}%...",
        "Generating Geology in background...": "Generiere Geologie im Hintergrund...",
        "Geological Profile": "Geologisches Profil",
        "Geology": "Geologie",
        "Geology configuration is incomplete": "Geologiekonfiguration unvollständig",
        "Geology: No data": "Geologie: Keine Daten",
        "Geology processing failed: {}": "Geologieverarbeitung fehlgeschlagen: {}",
        "Geology: {} segments": "Geologie: {} Segmente",
        "Geometry Range:": "Geometriebereich:",
        "Help file not found. Please run 'make doc' to generate it.": "Hilfedatei nicht gefunden. Bitte 'make doc' ausführen.",
        "Input Processing Error": "Eingabeverarbeitungsfehler",
        "Interpret": "Interpretieren",
        "Interpretation": "Interpretation",
        "Interpretation Properties": "Interpretationseigenschaften",
        "Interpretations (2D)": "Interpretationen (2D)",
        "Interpretation Settings": "Interpretationseinstellungen",
        "Invalid configuration": "Ungültige Konfiguration",
        "<i>Select which data to generate when clicking Save.</i>": "<i>Wählen Sie zu generierende Daten beim Speichern.</i>",
        " m": " m",
        "Maximum points to render in preview (LOD Optimization)": "Max Punkte Vorschau (LOD)",
        "Max Points:": "Max Punkte:",
        "Measure": "Messen",
        "Measure distance and slope": "Entfernung und Steigung messen",
        "{metadata['name']} v{metadata['version']}": "{metadata['name']} v{metadata['version']}",
        "Metadata missing": "Metadaten fehlen",
        "Name:": "Name:",
        "New Interpretation": "Neue Interpretation",
        "No layers to export.": "Keine Layer zum Exportieren.",
        "No preview available to export. Generate a preview first.": "Keine Vorschau verfügbar. Erst generieren.",
        "No profile data generated.": "Keine Profildaten generiert.",
        "Output directory path is required": "Ausgabeverzeichnis erforderlich",
        "Output Folder": "Ausgabeordner",
        "Performance:": "Leistung:",
        "Plugin Information": "Plugin-Informationen",
        "Plugin Settings": "Plugin-Einstellungen",
        "Preview Error": "Vorschaufehler",
        "Preview exported to {}": "Vorschau exportiert nach {}",
        "✓ Preview generated!": "✓ Vorschau generiert!",
        "Preview generated successfully": "Vorschau erfolgreich generiert",
        "Raster DEM layer is required": "Raster-DGM-Layer erforderlich",
        "Raster layer selected": "Raster-Layer ausgewählt",
        "Remove Field": "Feld entfernen",
        "Reset all inputs to their default values.": "Alles auf Standard zurücksetzen.",
        "Reset Defaults": "Standard herst.",
        "Scale 1: -": "Maßstab 1: -",
        "Scale 1:{}": "Maßstab 1:{}",
        "Sec Interp": "Sec Interp",
        "Sec Interp (version unavailable)": "Sec Interp (Vers. nicht verf.)",
        "Section Line": "Schnittlinie",
        "Section line selected": "Schnittlinie ausgewählt",
        "Select Color": "Farbe wählen",
        "Settings": "Einstellungen",
        "Show Interpretations": "Interpretationen anzeigen",
        "Show Legend": "Legende anzeigen",
        "Structural": "Strukturell",
        "Structural Data": "Strukturdaten",
        "Structure configuration is incomplete": "Strukturkonfiguration unvollständig",
        "Structures: {} measurements (buffer: {}m)": "Strukturen: {} Messungen (Puffer: {}m)",
        "Structures: No data": "Strukturen: Keine Daten",
        "Success": "Erfolg",
        "Topographic Profile": "Topographisches Profil",
        "Topography: {} points": "Topographie: {} Punkte",
        "Type": "Typ",
        "Type:": "Typ:",
        "Use adaptive sampling based on curvature (Phase 2)": "Adaptives Sampling (Phase 2)",
        "Use Original Coordinates (Real 3D)": "Originalkoordinaten nutzen (Echt-3D)",
        "Use Projected Coordinates (Section Plane)": "Projizierte Koordinaten nutzen (Schnittebene)",
        "Validation Error": "Validierungsfehler",
        "{}\n\nPlease check the logs for details.": "{}\n\nBitte prüfen Sie die Logs für Details.",
    },
    "ru": {
        "Adaptive": "Адаптивный",
        "Add Field": "Добавить Поле",
        "Advanced": "Дополнительно",
        "An unexpected error occurred: {}": "Произошла непредвиденная ошибка: {}",
        "Attribute Inheritance": "Наследование Атрибутов",
        "Auto": "Авто",
        "Auto-inherit from Drillhole intervals": "Авто-наследование интервалов скважин",
        "Auto-inherit from Geology layers": "Авто-наследование слоев геологии",
        "Automatically adjust details based on preview size": "Авто-настройка деталей по размеру",
        "Automatically copy rock code and attributes from the nearest drillhole interval.": "Копировать код породы/атрибуты из ближ. интервала.",
        "Automatically copy unit name and attributes from the nearest geology segment.": "Копировать имя/атрибуты из ближ. сегмента.",
        "✓ Cache cleared - next preview will re-process data": "✓ Кэш очищен - след. просмотр обновит данные",
        "⚠ Cache not available": "⚠ Кэш недоступен",
        "Change...": "Изменить...",
        "Clear cached data to force re-processing.": "Очистить кэш для пересчета.",
        "Color:": "Цвет:",
        "Configuration Error": "Ошибка Конфигурации",
        "Contact: {metadata['email']}": "Контакт: {metadata['email']}",
        "Coords: - , -": "Коорд: - , -",
        "Cross-section line layer is required": "Требуется слой линии сечения",
        "CRS: -": "СК: -",
        "CRS: {}": "СК: {}",
        "CRS: None": "СК: Нет",
        "CRS: Unknown": "СК: Неизвестна",
        "Custom Attributes": "Пользов. Атрибуты",
        "Default": "Стандарт",
        "Default Value": "Значение по умолч.",
        "DEM / Raster": "ЦМР / Растр",
        "Developed by {metadata['author']}": "Разработано {metadata['author']}",
        "  Distance: {} to {} m": "  Расст: {} до {} м",
        "Draw interpretation polygons": "Рисовать полигоны интерпретации",
        "Drillhole configuration is incomplete": "Конфигурация скважин неполная",
        "Drillhole Data": "Данные Скважин",
        "Drillholes": "Скважины",
        "Drillholes: {} holes found": "Скважины: найдено {}",
        "Drillholes: No data": "Скважины: Нет данных",
        "Duplicate field name: {}": "Дубликат имени поля: {}",
        "  Elevation: {} to {} m": "  Высота: {} до {} м",
        "Enable 3D Interpretation Export": "Вкл. Экспорт 3D Интерпретации",
        "Enables the generation of 3D Shapefiles (.shp) during export.": "Включает создание 3D Shapefiles (.shp) при экспорте.",
        "Error": "Ошибка",
        "Export 3D Intervals": "Экспорт 3D Интервалов",
        "Export 3D Traces": "Экспорт 3D Траекторий",
        "Export Error": "Ошибка Экспорта",
        "Export preview to file": "Экспорт предпросмотра в файл",
        "Field Name": "Имя Поля",
        "Field name cannot be empty": "Имя поля не может быть пустым",
        "Finalize": "Завершить",
        "Finalize multi-point measurement": "Завершить измерение",
        "✓ Form reset to default values": "✓ Форма сброшена",
        "Generating Drillholes in background...": "Генерация скважин в фоне...",
        "Generating Geology: {}%...": "Геология: {}%...",
        "Generating Geology in background...": "Генерация геологии в фоне...",
        "Geological Profile": "Геологический Профиль",
        "Geology": "Геология",
        "Geology configuration is incomplete": "Геология: конфиг неполный",
        "Geology: No data": "Геология: Нет данных",
        "Geology processing failed: {}": "Ошибка обработки геологии: {}",
        "Geology: {} segments": "Геология: {} сегментов",
        "Geometry Range:": "Диапазон Геометрии:",
        "Help file not found. Please run 'make doc' to generate it.": "Файл помощи не найден. Запустите 'make doc'.",
        "Input Processing Error": "Ошибка Обработки Ввода",
        "Interpret": "Интерпретация",
        "Interpretation": "Интерпретация",
        "Interpretation Properties": "Свойства Интерпретации",
        "Interpretations (2D)": "Интерпретации (2D)",
        "Interpretation Settings": "Настройки Интерпретации",
        "Invalid configuration": "Неверная конфигурация",
        "<i>Select which data to generate when clicking Save.</i>": "<i>Выберите данные для сохранения.</i>",
        " m": " м",
        "Maximum points to render in preview (LOD Optimization)": "Макс точек превью (LOD)",
        "Max Points:": "Макс Точек:",
        "Measure": "Измерить",
        "Measure distance and slope": "Измерить расстояние и уклон",
        "{metadata['name']} v{metadata['version']}": "{metadata['name']} v{metadata['version']}",
        "Metadata missing": "Нет метаданных",
        "Name:": "Имя:",
        "New Interpretation": "Новая Интерпретация",
        "No layers to export.": "Нет слоев для экспорта.",
        "No preview available to export. Generate a preview first.": "Нет превью. Сгенерируйте сначала.",
        "No profile data generated.": "Нет данных профиля.",
        "Output directory path is required": "Путь вывода обязателен",
        "Output Folder": "Папка Вывода",
        "Performance:": "Производительность:",
        "Plugin Information": "Инфо Плагина",
        "Plugin Settings": "Настройки Плагина",
        "Preview Error": "Ошибка Превью",
        "Preview exported to {}": "Превью экспортировано в {}",
        "✓ Preview generated!": "✓ Превью готово!",
        "Preview generated successfully": "Превью успешно создано",
        "Raster DEM layer is required": "Нужен слой ЦМР",
        "Raster layer selected": "Слой растра выбран",
        "Remove Field": "Удалить Поле",
        "Reset all inputs to their default values.": "Сбросить все в значения по умолчанию.",
        "Reset Defaults": "Сброс",
        "Scale 1: -": "Масштаб 1: -",
        "Scale 1:{}": "Масштаб 1:{}",
        "Sec Interp": "Sec Interp",
        "Sec Interp (version unavailable)": "Sec Interp (версия недоступна)",
        "Section Line": "Линия Сечения",
        "Section line selected": "Линия сечения выбрана",
        "Select Color": "Выбрать Цвет",
        "Settings": "Настройки",
        "Show Interpretations": "Показать Интерпретации",
        "Show Legend": "Показать Легенду",
        "Structural": "Структурные",
        "Structural Data": "Структурные Данные",
        "Structure configuration is incomplete": "Структуры: конфиг неполный",
        "Structures: {} measurements (buffer: {}m)": "Структуры: {} (буфер: {}м)",
        "Structures: No data": "Структуры: Нет данных",
        "Success": "Успех",
        "Topographic Profile": "Топографический Профиль",
        "Topography: {} points": "Топография: {} точек",
        "Type": "Тип",
        "Type:": "Тип:",
        "Use adaptive sampling based on curvature (Phase 2)": "Адаптивный сэмплинг (Фаза 2)",
        "Use Original Coordinates (Real 3D)": "Исп. Ориг. Координаты (Реальное 3D)",
        "Use Projected Coordinates (Section Plane)": "Исп. Проец. Координаты (План Сечения)",
        "Validation Error": "Ошибка Валидации",
        "{}\n\nPlease check the logs for details.": "{}\n\nПожалуйста, проверьте логи для деталей.",
    },
}

base_dir = Path("i18n")

for lang, translation_dict in langs.items():
    file_path = base_dir / f"SecInterp_{lang}.ts"
    if not file_path.exists():
        print(f"File not found: {file_path}")
        continue

    print(f"Processing {lang}...")
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()

        updated_count = 0

        for context in root.findall("context"):
            for message in context.findall("message"):
                source = message.find("source").text
                translation = message.find("translation")

                if (
                    source in translation_dict
                    and translation.get("type") == "unfinished"
                ):
                    translation.text = translation_dict[source]
                    # Remove the type="unfinished" attribute
                    del translation.attrib["type"]
                    updated_count += 1

        tree.write(file_path, encoding="utf-8", xml_declaration=True)
        print(f"Updated {updated_count} translations for {lang}")

    except Exception as e:
        print(f"Error processing {lang}: {e}")
